spring.application.name=usersService

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api/v1/users

jwt.secretKey=8f7c9a2e5d1b4c6f9a8e3d7b2c5f1a6e9d4b8c7f2a5e1d3c6b9f4a8e2d7c5b1